name: Android APK builder
on:
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: kevingopalan/action_android_build@v1
      with:
        GITHUB_TOKEN: # optional
        CI_TOKEN: # optional
        APP_NAME: # optional
        TYPEPACKAGE: # optional
