name: Android APK builder
on:
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    name: Android APK builder
  uses: kevingopalan/action_android_build@v1
  with:

    GITHUB_TOKEN: # optional

    CI_TOKEN: # optional

    APP_NAME: # optional

    TYPEPACKAGE: # optional
